# -*- coding: utf-8 -*-
"""proj113

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IC5Q-5T9AsKymjGP5ymggmAezKYRrRHg
"""

from google.colab import files 
data_to_load = files.upload()

import plotly.express as px
import pandas as pd

df = pd.read_csv("main.csv")
TOEFL = df["TOEFL Score"].tolist()
admitChance = df["Chance of Admit "].tolist()

fig = px.scatter(x=TOEFL, y = admitChance)
fig.show()

import numpy as np
TOEFL = np.array(TOEFL)
admitChance = np.array(admitChance)

m, c = np.polyfit(TOEFL, admitChance, 1)
y = []
for x in TOEFL:
  val = m*x+c
  y.append(val)

fig = px.scatter(x = TOEFL, y = admitChance)
fig.update_layout(shapes = [dict(
    type = "line",
    y0 = min(y),
    y1 = max(y),
    x0 = min(TOEFL),
    x1 = max(TOEFL)
)])
fig.show()

x = 100
y = m*x+c
print(f"TOEFL: {x} admitChance: {y}")